### PR TITLE
Add translations for new gamerules

### PR DESCRIPTION
**Pull request by ikyynites**
Add (english) translations for the new gamerules through lang files, simply to make them look more presentable, and polish them off as new features.

### CODE REVIEW

**Comment by moltenwolfcub** [comment]
Literally was just about to make this change myself after seeing Matt's video

**Review by Matthias1590 — APPROVED** [review]

**Review by Matthias1590 — APPROVED** [review]

**Comment by moltenwolfcub** [comment]
probably want to add 2 more translations:
`gamerule.doContainerDrops.description`
`gamerule.doBlockUpdatesAfterEdit.description`

to add descriptions on the create new world gamerule screen

**Comment by ikyynites** [comment]
can do quickly, ill make a suitable translation for them

**Comment by moltenwolfcub** [comment]
something like `Controls resource drops from containers` to fit with vanilla?

**Comment by ikyynites** [comment]
yes, thats what ive done, and also `Force update blocks after pasting them in WorldEdit` for `gamerule.doBlockUpdatesAfterEdit`

**Comment by ikyynites** [comment]
ehh, i suppose i could have worded that one a bit better

**Comment by moltenwolfcub** [comment]
It does the job and explains the gamerules purpose so it works

**Pull request merged**
